# Generated by Django 5.1.4 on 2024-12-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='deezer_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID de Deezer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='app.artist', verbose_name='Artista'),
        ),
    ]
