# Generated by Django 5.1.4 on 2024-12-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_artist_deezer_id_alter_song_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Artista'),
        ),
        migrations.AlterField(
            model_name='song',
            name='deezer_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID de Deezer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='numPlays',
            field=models.IntegerField(default=1, verbose_name='Número de Reproducciones'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título de la Canción'),
        ),
    ]
